
name: Cortex CLI Code Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  CORTEX_API_KEY: ${{ secrets.CORTEX_API_KEY }}
  CORTEX_API_KEY_ID: ${{ secrets.CORTEX_API_KEY_ID }}
  CORTEX_API_URL: https://api-viso-uj4hnragka6qmuubfe9v7c.xdr-qa2-uat.us.paloaltonetworks.com
  CORTEX_CLI_VERSION: 0.11.8
  
jobs:
  download-and-execute:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Get Temporary Token
      run: |
        TOKEN_RESPONSE=$(curl --location "${CORTEX_API_URL}/public_api/cas/v1/cortex-cli/create-token" \
          --header "Authorization: ${CORTEX_API_KEY}" \
          --header "x-xdr-auth-id: ${CORTEX_API_KEY_ID}" \
          --header 'Content-Type: application/json' \
          --data '{}')
        TEMP_TOKEN=$(echo $TOKEN_RESPONSE | jq -r '.token')
        echo "TEMP_TOKEN=$TEMP_TOKEN" >> $GITHUB_ENV
    - name: Pull Docker Image
      run: |
        docker pull distributions-dev.traps.paloaltonetworks.com/cli-docker/${{ env.TEMP_TOKEN }}/method:arm64-${{ env.CORTEX_CLI_VERSION }}-dev
        docker tag distributions-dev.traps.paloaltonetworks.com/cli-docker/${{ env.TEMP_TOKEN }}/method:arm64-${{ env.CORTEX_CLI_VERSION }}-dev cortexcli:${{ env.CORTEX_CLI_VERSION }}
    - name: Run Docker Container
      run: |
        docker run --rm -v ${{ github.workspace }}:/home/code cortexcli:${{ env.CORTEX_CLI_VERSION }} \
          --api-base-url ${CORTEX_API_URL} \
          --api-key ${CORTEX_API_KEY} \
          --api-key-id ${CORTEX_API_KEY_ID} \
          --log-level error \
          --soft-fail \
          code scan \
          --directory /home/code \
          --branch ${{ github.head_ref || github.ref_name }} \
          --repo-id dsarafpa/DanitGitHub_260325 \
          --source 'GITHUB_ACTIONS' \
          --create-repo-if-missing 
          
